start /b download https://www.thingjs.com/guide/official/js/basic_helloworld.js   -o D:/Desktop/aasdfsadf  #HelloWorld
start /b download https://www.thingjs.com/guide/official/js/basic_entity.js   -o D:/Desktop/aasdfsadf  #加载模型
start /b download https://www.thingjs.com/guide/official/js/basic_style.js   -o D:/Desktop/aasdfsadf  #物体样式
start /b download https://www.thingjs.com/guide/official/js/basic_event.js   -o D:/Desktop/aasdfsadf  #添加事件
start /b download https://www.thingjs.com/guide/official/js/basic_com.js   -o D:/Desktop/aasdfsadf  #添加组件
start /b download https://www.thingjs.com/guide/official/js/basic_light.js   -o D:/Desktop/aasdfsadf  #设置灯光
start /b download https://www.thingjs.com/guide/official/js/basic_component.js   -o D:/Desktop/aasdfsadf  #自定义组件
start /b download https://www.thingjs.com/guide/official/js/basic_query.js   -o D:/Desktop/aasdfsadf  #使用查询
start /b download https://www.thingjs.com/guide/official/js/basic_camera.js   -o D:/Desktop/aasdfsadf  #认识摄像机
start /b download https://www.thingjs.com/guide/official/js/basic_marker.js   -o D:/Desktop/aasdfsadf  #认识标记
start /b download https://www.thingjs.com/guide/official/js/basic_campus.js   -o D:/Desktop/aasdfsadf  #加载场景
start /b download https://www.thingjs.com/guide/official/js/geometry_points.js   -o D:/Desktop/aasdfsadf  #点
start /b download https://www.thingjs.com/guide/official/js/geometry_lines.js   -o D:/Desktop/aasdfsadf  #线
start /b download https://www.thingjs.com/guide/official/js/geometry_plane.js   -o D:/Desktop/aasdfsadf  #平面
start /b download https://www.thingjs.com/guide/official/js/geometry_diverse.js   -o D:/Desktop/aasdfsadf  #多种几何体
start /b download https://www.thingjs.com/guide/official/js/object_style.js   -o D:/Desktop/aasdfsadf  #设置样式
start /b download https://www.thingjs.com/guide/official/js/object_instanced.js   -o D:/Desktop/aasdfsadf  #批量创建物体
start /b download https://www.thingjs.com/guide/official/js/object_query.js   -o D:/Desktop/aasdfsadf  #查询物体
start /b download https://www.thingjs.com/guide/official/js/object_animation.js   -o D:/Desktop/aasdfsadf  #物体动画
start /b download https://www.thingjs.com/guide/official/js/object_boundingBox.js   -o D:/Desktop/aasdfsadf  #包围盒
start /b download https://www.thingjs.com/guide/official/js/object_pivot.js   -o D:/Desktop/aasdfsadf  #物体轴心点
start /b download https://www.thingjs.com/guide/official/js/object_subObjects.js   -o D:/Desktop/aasdfsadf  #物体子节点
start /b download https://www.thingjs.com/guide/official/js/object_attachedPoint.js   -o D:/Desktop/aasdfsadf  #挂点物体
start /b download https://www.thingjs.com/guide/official/js/object_destroy.js   -o D:/Desktop/aasdfsadf  #销毁物体
start /b download https://www.thingjs.com/guide/official/js/event_mouse.js   -o D:/Desktop/aasdfsadf  #鼠标事件
start /b download https://www.thingjs.com/guide/official/js/event_keyBoard.js   -o D:/Desktop/aasdfsadf  #键盘事件
start /b download https://www.thingjs.com/guide/official/js/event_off.js   -o D:/Desktop/aasdfsadf  #开启关闭事件
start /b download https://www.thingjs.com/guide/official/js/marker_textLabel.js   -o D:/Desktop/aasdfsadf  #文字标签
start /b download https://www.thingjs.com/guide/official/js/marker_label.js   -o D:/Desktop/aasdfsadf  #标签
start /b download https://www.thingjs.com/guide/official/js/camera_viewMode.js   -o D:/Desktop/aasdfsadf  #摄像机视角
start /b download https://www.thingjs.com/guide/official/js/camera_changeProjection.js   -o D:/Desktop/aasdfsadf  #摄像机投影方式
start /b download https://www.thingjs.com/guide/official/js/camera_fog.js   -o D:/Desktop/aasdfsadf  #雾
start /b download https://www.thingjs.com/guide/official/js/camera_earth.js   -o D:/Desktop/aasdfsadf  #地球相机
start /b download https://www.thingjs.com/guide/official/js/create_earth.js   -o D:/Desktop/aasdfsadf  #创建地球
start /b download https://www.thingjs.com/guide/official/js/tileLayer.js   -o D:/Desktop/aasdfsadf  #瓦片图层
start /b download https://www.thingjs.com/guide/official/js/load_scene.js   -o D:/Desktop/aasdfsadf  #场景加载
start /b download https://www.thingjs.com/guide/official/js/create_mapPoint.js   -o D:/Desktop/aasdfsadf  #创建地图点
start /b download https://www.thingjs.com/guide/official/js/create_mapLine.js   -o D:/Desktop/aasdfsadf  #创建地图线
start /b download https://www.thingjs.com/guide/official/js/create_mapFlyLine.js   -o D:/Desktop/aasdfsadf  #创建地图飞线
start /b download https://www.thingjs.com/guide/official/js/create_mapPolygon.js   -o D:/Desktop/aasdfsadf  #创建地图多边形
start /b download https://www.thingjs.com/guide/official/js/create_mapArchitecture.js   -o D:/Desktop/aasdfsadf  #创建地图建筑
start /b download https://www.thingjs.com/guide/official/js/create_mapWaterSurface.js   -o D:/Desktop/aasdfsadf  #创建地图水面
start /b download https://www.thingjs.com/guide/official/js/create_mapRail.js   -o D:/Desktop/aasdfsadf  #创建地图围栏
start /b download https://www.thingjs.com/guide/official/js/FeatureLayer_mapPoints.js   -o D:/Desktop/aasdfsadf  #FeatureLayer地图点
start /b download https://www.thingjs.com/guide/official/js/FeatureLayer_mapLines.js   -o D:/Desktop/aasdfsadf  #FeatureLayer地图线
start /b download https://www.thingjs.com/guide/official/js/FeatureLayer_mapPolygon.js   -o D:/Desktop/aasdfsadf  #FeatureLayer地图多边形
start /b download https://www.thingjs.com/guide/official/js/FeatureLayer_mapArchitecture.js   -o D:/Desktop/aasdfsadf  #FeatureLayer地图建筑
start /b download https://www.thingjs.com/guide/official/js/map_thermodynamicChart.js   -o D:/Desktop/aasdfsadf  #地图热力图
start /b download https://www.thingjs.com/guide/official/js/map_label.js   -o D:/Desktop/aasdfsadf  #地图标注
start /b download https://www.thingjs.com/guide/official/js/information_panel.js   -o D:/Desktop/aasdfsadf  #信息面板
start /b download https://www.thingjs.com/guide/official/js/move_alongTrajectory.js   -o D:/Desktop/aasdfsadf  #地球上沿轨迹移动
start /b download https://www.thingjs.com/guide/official/js/map_compass.js   -o D:/Desktop/aasdfsadf  #地球指北针
start /b download https://www.thingjs.com/guide/official/js/create_mapThroughUrl.js   -o D:/Desktop/aasdfsadf  #通过url方式创建地图
start /b download https://www.thingjs.com/guide/official/js/component_transformControl.js   -o D:/Desktop/aasdfsadf  #变换组件
start /b download https://www.thingjs.com/guide/official/js/stage_show.js   -o D:/Desktop/aasdfsadf  #舞台场景展示
start /b download https://www.thingjs.com/guide/official/js/samples_component.js   -o D:/Desktop/aasdfsadf  #组件示例
start /b download https://www.thingjs.com/guide/official/js/samples_collider.js   -o D:/Desktop/aasdfsadf  #碰撞检测
start /b download https://www.thingjs.com/guide/official/js/samples_prefab.js   -o D:/Desktop/aasdfsadf  #预制件
start /b download https://www.thingjs.com/guide/official/js/samples_plugin.js   -o D:/Desktop/aasdfsadf  #插件示例
start /b download https://www.thingjs.com/guide/official/js/samples_multipleCamera.js   -o D:/Desktop/aasdfsadf  #多摄像机
start /b download https://www.thingjs.com/guide/official/js/samples_renderTexture.js   -o D:/Desktop/aasdfsadf  #渲染纹理
start /b download https://www.thingjs.com/guide/official/js/samples_videoTexture.js   -o D:/Desktop/aasdfsadf  #视频纹理
start /b download https://www.thingjs.com/guide/official/js/samples_fatLine.js   -o D:/Desktop/aasdfsadf  #等像素粗线
start /b download https://www.thingjs.com/guide/official/js/samples_extrudeshape.js   -o D:/Desktop/aasdfsadf  #拉伸形状物体
start /b download https://www.thingjs.com/guide/official/js/samples_instanceBox.js   -o D:/Desktop/aasdfsadf  #批量渲染盒子
start /b download https://www.thingjs.com/guide/official/js/samples_instanceCar.js   -o D:/Desktop/aasdfsadf  #批量渲染小车
start /b download https://www.thingjs.com/guide/official/js/samples_sceneBundle.js   -o D:/Desktop/aasdfsadf  #场景包
start /b download https://www.thingjs.com/guide/official/js/samples_water.js   -o D:/Desktop/aasdfsadf  #水
start /b download https://www.thingjs.com/guide/official/js/sampleB_01_Hello.js   -o D:/Desktop/aasdfsadf  #HelloWorld(100%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_01_Debugger.js   -o D:/Desktop/aasdfsadf  #调试(100%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_01_DynamicLoad.js   -o D:/Desktop/aasdfsadf  #引用 js 和 css(100%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_02_SceneLevelLook.js   -o D:/Desktop/aasdfsadf  #展示场景层级(100%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_02_BuildingExpandOut.js   -o D:/Desktop/aasdfsadf  #展示建筑外部结构(100%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_02_BuildingExpandInner.js   -o D:/Desktop/aasdfsadf  #展示建筑内部结构(100%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_02_SceneLevelControl.js   -o D:/Desktop/aasdfsadf  #场景层级控制(100%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_02_SceneDynamicLoad.js   -o D:/Desktop/aasdfsadf  #场景动态加载(90%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_02_Background.js   -o D:/Desktop/aasdfsadf  #设置背景(100%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_02_spotlight.js   -o D:/Desktop/aasdfsadf  #设置聚光灯(100%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_02_BIM.js   -o D:/Desktop/aasdfsadf  #
start /b download https://www.thingjs.com/guide/official/js/sampleB_03_earth_putSceneOn.js   -o D:/Desktop/aasdfsadf  #加载场景(100%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_03_Earth_Query.js   -o D:/Desktop/aasdfsadf  #查询地图对象(80%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_03_Earth_AddLayer.js   -o D:/Desktop/aasdfsadf  #创建图层(100%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_03_earth_PointLayerStyle.js   -o D:/Desktop/aasdfsadf  #修改点图层样式(100%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_03_earth_LineLayerStyle.js   -o D:/Desktop/aasdfsadf  #修改线图层样式(100%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_03_earth_FaceLayerStyle.js   -o D:/Desktop/aasdfsadf  #修改面图层样式(100%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_03_earth_BuildingLayerStyle.js   -o D:/Desktop/aasdfsadf  #修改建筑图层样式(100%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_03_earth_changeTileLayer.js   -o D:/Desktop/aasdfsadf  #修改地图底图(100%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_03_earth_tileLayerStyle.js   -o D:/Desktop/aasdfsadf  #设置底图效果(100%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_03_earth_infoWindow.js   -o D:/Desktop/aasdfsadf  #自定义信息面板(100%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_03_earth_terrainLayer.js   -o D:/Desktop/aasdfsadf  #创建地形图层(100%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_03_earth_Tile3dLayer.js   -o D:/Desktop/aasdfsadf  #创建倾斜摄影图层(100%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_03_earth_fireworks.js   -o D:/Desktop/aasdfsadf  #烟花图(100%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_03_earth_columnar.js   -o D:/Desktop/aasdfsadf  #柱状体(100%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_03_earth_navigate.js   -o D:/Desktop/aasdfsadf  #路径导航（高德）(100%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_03_earth_heatmap.js   -o D:/Desktop/aasdfsadf  #地图热力图(100%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_04_MouseEvents.js   -o D:/Desktop/aasdfsadf  #鼠标事件(100%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_04_KeyEvents.js   -o D:/Desktop/aasdfsadf  #键盘事件(100%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_04_EarthEvents.js   -o D:/Desktop/aasdfsadf  #地图事件(100%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_05_Thing.js   -o D:/Desktop/aasdfsadf  #创建物体(100%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_05_Line.js   -o D:/Desktop/aasdfsadf  #创建线(100%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_05_Plane.js   -o D:/Desktop/aasdfsadf  #创建面(100%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_05_Particle.js   -o D:/Desktop/aasdfsadf  #创建粒子(100%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_05_Query.js   -o D:/Desktop/aasdfsadf  #查询对象(100%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_05_Style.js   -o D:/Desktop/aasdfsadf  #设置物体效果(100%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_05_Animations.js   -o D:/Desktop/aasdfsadf  #物体动画(100%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_05_CustomClass.js   -o D:/Desktop/aasdfsadf  #自定义类物体(90%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_05_PickRegion.js   -o D:/Desktop/aasdfsadf  #框选物体(100%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_05_PickOnly.js   -o D:/Desktop/aasdfsadf  #拾取室内物体(100%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_05_ExplosiveView.js   -o D:/Desktop/aasdfsadf  #爆炸图(80%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_05_ExplosiveView2.js   -o D:/Desktop/aasdfsadf  #爆炸图2(100%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_06_Cameraflys.js   -o D:/Desktop/aasdfsadf  #控制飞行(100%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_06_CameraLimits.js   -o D:/Desktop/aasdfsadf  #控制交互(100%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_06_earth_camera.js   -o D:/Desktop/aasdfsadf  #控制地球相机(100%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_07_UI.js   -o D:/Desktop/aasdfsadf  #内置界面(100%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_07_EChartsUI.js   -o D:/Desktop/aasdfsadf  #ECharts 界面(100%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_07_Banner.js   -o D:/Desktop/aasdfsadf  #通栏(100%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_07_ClassUI.js   -o D:/Desktop/aasdfsadf  #内置标注(100%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_07_Label.js   -o D:/Desktop/aasdfsadf  #普通标注(100%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_07_LabelAnimation.js   -o D:/Desktop/aasdfsadf  #标注动画(100%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_07_WebView.js   -o D:/Desktop/aasdfsadf  #内嵌页面(100%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_07_IframeSameOrigin.js   -o D:/Desktop/aasdfsadf  #引用同域页面(100%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_07_IframeCrossOrigin.js   -o D:/Desktop/aasdfsadf  #引用跨域页面(100%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_07_Iframe3D.js   -o D:/Desktop/aasdfsadf  #用户页面嵌3D(100%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_09_MiniMap.js   -o D:/Desktop/aasdfsadf  #小地图(100%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_09_FPS.js   -o D:/Desktop/aasdfsadf  #第一人称行走(80%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_09_DoubleCamera.js   -o D:/Desktop/aasdfsadf  #双摄像机(90%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_09_FPS_fly.js   -o D:/Desktop/aasdfsadf  #自由飞行(100%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_09_Share.js   -o D:/Desktop/aasdfsadf  #分享(100%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_09_GetData_Ajax_CORS.js   -o D:/Desktop/aasdfsadf  #数据对接_Ajax(100%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_09_GetData_JSONP.js   -o D:/Desktop/aasdfsadf  #数据对接_JSONP(100%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_09_GetData_WebSocket.js   -o D:/Desktop/aasdfsadf  #数据对接_WebSocket(100%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_09_GetData_MQTT.js   -o D:/Desktop/aasdfsadf  #数据对接_MQTT(100%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_10_Audio.js   -o D:/Desktop/aasdfsadf  #播放音频(100%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_10_VideoSurveillance.js   -o D:/Desktop/aasdfsadf  #播放视频(100%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_15_cameraProjector.js   -o D:/Desktop/aasdfsadf  #视频融合(80%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_11_MeasureDistance.js   -o D:/Desktop/aasdfsadf  #测距离(90%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_11_MeasureArea.js   -o D:/Desktop/aasdfsadf  #测面积(90%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_11_ElectronicFence.js   -o D:/Desktop/aasdfsadf  #电子围栏(100%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_11_CuttingPlane.js   -o D:/Desktop/aasdfsadf  #剖切面(100%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_11_CuttingBox.js   -o D:/Desktop/aasdfsadf  #剖切盒(0%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_11_SceneTopCard.js   -o D:/Desktop/aasdfsadf  #场景显示顶牌(0%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_11_SimulationNavigation.js   -o D:/Desktop/aasdfsadf  #室内导航（点击定位）(0%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_11_NavigationInfomationQuery.js   -o D:/Desktop/aasdfsadf  #室内导航（查询定位）(0%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_11_RealNavigation.js   -o D:/Desktop/aasdfsadf  #室内导航（真实导航）(0%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_11_pano.js   -o D:/Desktop/aasdfsadf  #全景图(0%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_02_DynamicCreateObject.js   -o D:/Desktop/aasdfsadf  #动态加载管理对象(100%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_02_PanelLoad.js   -o D:/Desktop/aasdfsadf  #批量显示监控牌(100%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_02_OpenObjectPanel.js   -o D:/Desktop/aasdfsadf  #物体面板显示监控(100%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_silohouse.js   -o D:/Desktop/aasdfsadf  #粮仓管理(90%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_comproom.js   -o D:/Desktop/aasdfsadf  #机房管理(100%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_uBuilding.js   -o D:/Desktop/aasdfsadf  #建筑监控(100%)
start /b download https://www.thingjs.com/guide/official/js/sampleB_12_earth_simpleDemo.js   -o D:/Desktop/aasdfsadf  #地球综合(90%)