start /b download https://www.thingjs.com/guide/examples/js/sample_01_Hello.js   -o D:/Desktop/11aasdfsadf #HelloWorld
start /b download https://www.thingjs.com/guide/examples/js/sample_01_Debugger.js   -o D:/Desktop/11aasdfsadf #调试
start /b download https://www.thingjs.com/guide/examples/js/sample_01_DynamicLoad.js   -o D:/Desktop/11aasdfsadf #引用 js 和 css
start /b download https://www.thingjs.com/guide/examples/js/sample_02_SceneLevelLook.js   -o D:/Desktop/11aasdfsadf #展示场景层级
start /b download https://www.thingjs.com/guide/examples/js/sample_02_BuildingExpandOut.js   -o D:/Desktop/11aasdfsadf #展示建筑外部结构
start /b download https://www.thingjs.com/guide/examples/js/sample_02_BuildingExpandInner.js   -o D:/Desktop/11aasdfsadf #展示建筑内部结构
start /b download https://www.thingjs.com/guide/examples/js/sample_02_SceneLevelControl.js   -o D:/Desktop/11aasdfsadf #场景层级控制
start /b download https://www.thingjs.com/guide/examples/js/sample_02_SceneDynamicLoad.js   -o D:/Desktop/11aasdfsadf #场景动态加载
start /b download https://www.thingjs.com/guide/examples/js/sample_02_Background.js   -o D:/Desktop/11aasdfsadf #设置背景
start /b download https://www.thingjs.com/guide/examples/js/sample_02_spotlight.js   -o D:/Desktop/11aasdfsadf #设置聚光灯
start /b download https://www.thingjs.com/guide/examples/js/sample_02_BIM.js   -o D:/Desktop/11aasdfsadf #BIM场景
start /b download https://www.thingjs.com/guide/examples/js/sample_02_EffectThemeControl.js   -o D:/Desktop/11aasdfsadf #场景效果模板
start /b download https://www.thingjs.com/guide/examples/js/sample_03_earth_putSceneOn.js   -o D:/Desktop/11aasdfsadf #加载场景
start /b download https://www.thingjs.com/guide/examples/js/sample_03_Earth_Query.js   -o D:/Desktop/11aasdfsadf #查询地图对象
start /b download https://www.thingjs.com/guide/examples/js/sample_03_Earth_AddLayer.js   -o D:/Desktop/11aasdfsadf #创建图层
start /b download https://www.thingjs.com/guide/examples/js/sample_03_earth_PointLayerStyle.js   -o D:/Desktop/11aasdfsadf #修改点图层样式
start /b download https://www.thingjs.com/guide/examples/js/sample_03_earth_LineLayerStyle.js   -o D:/Desktop/11aasdfsadf #修改线图层样式
start /b download https://www.thingjs.com/guide/examples/js/sample_03_earth_FaceLayerStyle.js   -o D:/Desktop/11aasdfsadf #修改面图层样式
start /b download https://www.thingjs.com/guide/examples/js/sample_03_earth_BuildingLayerStyle.js   -o D:/Desktop/11aasdfsadf #修改建筑图层样式
start /b download https://www.thingjs.com/guide/examples/js/sample_03_earth_changeTileLayer.js   -o D:/Desktop/11aasdfsadf #修改地图底图
start /b download https://www.thingjs.com/guide/examples/js/sample_03_earth_tileLayerStyle.js   -o D:/Desktop/11aasdfsadf #设置底图效果
start /b download https://www.thingjs.com/guide/examples/js/sample_03_earth_infoWindow.js   -o D:/Desktop/11aasdfsadf #自定义信息面板
start /b download https://www.thingjs.com/guide/examples/js/sample_03_earth_terrainLayer.js   -o D:/Desktop/11aasdfsadf #创建地形图层
start /b download https://www.thingjs.com/guide/examples/js/sample_03_earth_Tile3dLayer.js   -o D:/Desktop/11aasdfsadf #创建倾斜摄影图层
start /b download https://www.thingjs.com/guide/examples/js/sample_03_earth_PointCloud.js   -o D:/Desktop/11aasdfsadf #创建点云图层
start /b download https://www.thingjs.com/guide/examples/js/sample_03_earth_fireworks.js   -o D:/Desktop/11aasdfsadf #烟花图
start /b download https://www.thingjs.com/guide/examples/js/sample_03_earth_columnar.js   -o D:/Desktop/11aasdfsadf #柱状体
start /b download https://www.thingjs.com/guide/examples/js/sample_03_earth_navigate.js   -o D:/Desktop/11aasdfsadf #路径导航（高德）
start /b download https://www.thingjs.com/guide/examples/js/sample_03_earth_heatmap.js   -o D:/Desktop/11aasdfsadf #地图热力图
start /b download https://www.thingjs.com/guide/examples/js/sample_17_topo_graphControl.js   -o D:/Desktop/11aasdfsadf #画布操作
start /b download https://www.thingjs.com/guide/examples/js/sample_17_topo_query.js   -o D:/Desktop/11aasdfsadf #获取对象
start /b download https://www.thingjs.com/guide/examples/js/sample_17_topo_nodeAttribute.js   -o D:/Desktop/11aasdfsadf #修改节点属性
start /b download https://www.thingjs.com/guide/examples/js/sample_17_topo_nodeAnimation1.js   -o D:/Desktop/11aasdfsadf #节点动画一
start /b download https://www.thingjs.com/guide/examples/js/sample_17_topo_nodeAnimation2.js   -o D:/Desktop/11aasdfsadf #节点动画二
start /b download https://www.thingjs.com/guide/examples/js/sample_17_topo_lineAttribute.js   -o D:/Desktop/11aasdfsadf #修改连线属性
start /b download https://www.thingjs.com/guide/examples/js/sample_17_topo_lineAnimation.js   -o D:/Desktop/11aasdfsadf #连线动画
start /b download https://www.thingjs.com/guide/examples/js/sample_17_topo_event.js   -o D:/Desktop/11aasdfsadf #鼠标事件
start /b download https://www.thingjs.com/guide/examples/js/sample_04_MouseEvents.js   -o D:/Desktop/11aasdfsadf #鼠标事件
start /b download https://www.thingjs.com/guide/examples/js/sample_04_KeyEvents.js   -o D:/Desktop/11aasdfsadf #键盘事件
start /b download https://www.thingjs.com/guide/examples/js/sample_04_EarthEvents.js   -o D:/Desktop/11aasdfsadf #地图事件
start /b download https://www.thingjs.com/guide/examples/js/sample_05_Thing.js   -o D:/Desktop/11aasdfsadf #创建物体
start /b download https://www.thingjs.com/guide/examples/js/sample_05_Line.js   -o D:/Desktop/11aasdfsadf #创建线
start /b download https://www.thingjs.com/guide/examples/js/sample_05_Plane.js   -o D:/Desktop/11aasdfsadf #创建面
start /b download https://www.thingjs.com/guide/examples/js/sample_05_Particle.js   -o D:/Desktop/11aasdfsadf #创建粒子
start /b download https://www.thingjs.com/guide/examples/js/sample_05_Query.js   -o D:/Desktop/11aasdfsadf #查询对象
start /b download https://www.thingjs.com/guide/examples/js/sample_05_Style.js   -o D:/Desktop/11aasdfsadf #设置物体效果
start /b download https://www.thingjs.com/guide/examples/js/sample_05_Animations.js   -o D:/Desktop/11aasdfsadf #物体动画
start /b download https://www.thingjs.com/guide/examples/js/sample_05_CustomClass.js   -o D:/Desktop/11aasdfsadf #自定义类物体
start /b download https://www.thingjs.com/guide/examples/js/sample_05_PickRegion.js   -o D:/Desktop/11aasdfsadf #框选物体
start /b download https://www.thingjs.com/guide/examples/js/sample_05_PickOnly.js   -o D:/Desktop/11aasdfsadf #拾取室内物体
start /b download https://www.thingjs.com/guide/examples/js/sample_05_ExplosiveView.js   -o D:/Desktop/11aasdfsadf #爆炸图
start /b download https://www.thingjs.com/guide/examples/js/sample_05_ExplosiveView2.js   -o D:/Desktop/11aasdfsadf #爆炸图2
start /b download https://www.thingjs.com/guide/examples/js/sample_06_Cameraflys.js   -o D:/Desktop/11aasdfsadf #控制飞行
start /b download https://www.thingjs.com/guide/examples/js/sample_06_CameraLimits.js   -o D:/Desktop/11aasdfsadf #控制交互
start /b download https://www.thingjs.com/guide/examples/js/sample_06_earth_camera.js   -o D:/Desktop/11aasdfsadf #控制地球相机
start /b download https://www.thingjs.com/guide/examples/js/sample_07_UI.js   -o D:/Desktop/11aasdfsadf #内置界面
start /b download https://www.thingjs.com/guide/examples/js/sample_07_EChartsUI.js   -o D:/Desktop/11aasdfsadf #ECharts 界面
start /b download https://www.thingjs.com/guide/examples/js/sample_07_Banner.js   -o D:/Desktop/11aasdfsadf #通栏
start /b download https://www.thingjs.com/guide/examples/js/sample_07_ClassUI.js   -o D:/Desktop/11aasdfsadf #内置标注
start /b download https://www.thingjs.com/guide/examples/js/sample_07_Label.js   -o D:/Desktop/11aasdfsadf #普通标注
start /b download https://www.thingjs.com/guide/examples/js/sample_07_LabelAnimation.js   -o D:/Desktop/11aasdfsadf #标注动画
start /b download https://www.thingjs.com/guide/examples/js/sample_07_WebView.js   -o D:/Desktop/11aasdfsadf #内嵌页面
start /b download https://www.thingjs.com/guide/examples/js/sample_07_IframeSameOrigin.js   -o D:/Desktop/11aasdfsadf #引用同域页面
start /b download https://www.thingjs.com/guide/examples/js/sample_07_IframeCrossOrigin.js   -o D:/Desktop/11aasdfsadf #引用跨域页面
start /b download https://www.thingjs.com/guide/examples/js/sample_07_Iframe3D.js   -o D:/Desktop/11aasdfsadf #用户页面嵌3D
start /b download https://www.thingjs.com/guide/examples/js/sample_09_MiniMap.js   -o D:/Desktop/11aasdfsadf #小地图
start /b download https://www.thingjs.com/guide/examples/js/sample_09_FPS.js   -o D:/Desktop/11aasdfsadf #第一人称行走
start /b download https://www.thingjs.com/guide/examples/js/sample_09_DoubleCamera.js   -o D:/Desktop/11aasdfsadf #双摄像机
start /b download https://www.thingjs.com/guide/examples/js/sample_09_FPS_fly.js   -o D:/Desktop/11aasdfsadf #自由飞行
start /b download https://www.thingjs.com/guide/examples/js/sample_09_Share.js   -o D:/Desktop/11aasdfsadf #分享
start /b download https://www.thingjs.com/guide/examples/js/sample_09_GetData_Ajax_CORS.js   -o D:/Desktop/11aasdfsadf #数据对接_Ajax
start /b download https://www.thingjs.com/guide/examples/js/sample_09_GetData_JSONP.js   -o D:/Desktop/11aasdfsadf #数据对接_JSONP
start /b download https://www.thingjs.com/guide/examples/js/sample_09_GetData_WebSocket.js   -o D:/Desktop/11aasdfsadf #数据对接_WebSocket
start /b download https://www.thingjs.com/guide/examples/js/sample_09_GetData_MQTT.js   -o D:/Desktop/11aasdfsadf #数据对接_MQTT
start /b download https://www.thingjs.com/guide/examples/js/sample_09_GetData_QC.js   -o D:/Desktop/11aasdfsadf #QChart图表数据对接
start /b download https://www.thingjs.com/guide/examples/js/sample_10_Audio.js   -o D:/Desktop/11aasdfsadf #播放音频
start /b download https://www.thingjs.com/guide/examples/js/sample_10_VideoSurveillance.js   -o D:/Desktop/11aasdfsadf #播放视频
start /b download https://www.thingjs.com/guide/examples/js/sample_15_cameraProjector.js   -o D:/Desktop/11aasdfsadf #视频融合
start /b download https://www.thingjs.com/guide/examples/js/sample_11_MeasureDistance.js   -o D:/Desktop/11aasdfsadf #测距离
start /b download https://www.thingjs.com/guide/examples/js/sample_11_MeasureArea.js   -o D:/Desktop/11aasdfsadf #测面积
start /b download https://www.thingjs.com/guide/examples/js/sample_11_ElectronicFence.js   -o D:/Desktop/11aasdfsadf #电子围栏
start /b download https://www.thingjs.com/guide/examples/js/sample_11_CuttingPlane.js   -o D:/Desktop/11aasdfsadf #剖切面
start /b download https://www.thingjs.com/guide/examples/js/sample_11_CuttingBox.js   -o D:/Desktop/11aasdfsadf #剖切盒
start /b download https://www.thingjs.com/guide/examples/js/sample_11_SceneTopCard.js   -o D:/Desktop/11aasdfsadf #场景显示顶牌
start /b download https://www.thingjs.com/guide/examples/js/sample_11_SimulationNavigation.js   -o D:/Desktop/11aasdfsadf #室内导航（点击定位）
start /b download https://www.thingjs.com/guide/examples/js/sample_11_NavigationInfomationQuery.js   -o D:/Desktop/11aasdfsadf #室内导航（查询定位）
start /b download https://www.thingjs.com/guide/examples/js/sample_11_RealNavigation.js   -o D:/Desktop/11aasdfsadf #室内导航（真实导航）
start /b download https://www.thingjs.com/guide/examples/js/sample_11_pano.js   -o D:/Desktop/11aasdfsadf #全景图
start /b download https://www.thingjs.com/guide/examples/js/sample_02_DynamicCreateObject.js   -o D:/Desktop/11aasdfsadf #动态加载管理对象
start /b download https://www.thingjs.com/guide/examples/js/sample_02_PanelLoad.js   -o D:/Desktop/11aasdfsadf #批量显示监控牌
start /b download https://www.thingjs.com/guide/examples/js/sample_02_OpenObjectPanel.js   -o D:/Desktop/11aasdfsadf #物体面板显示监控
start /b download https://www.thingjs.com/guide/examples/js/sample_12_earth_simpleDemo.js   -o D:/Desktop/11aasdfsadf #地球综合